#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 "sudo docker exec ai-mt5-vnc bash -c \"cp -v -f /headless/Desktop/Aurum_EA/AurumAI_Executor.mq5 '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/' && chown -R kasm-user:kasm-user /headless/.wine\""
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}
