#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 "sudo docker exec -u kasm-user -e DISPLAY=:1 -e WINEPREFIX=/headless/.wine ai-mt5-vnc wine cmd /c 'cd /d \"C:\\Program Files\\MetaTrader 5\" && metaeditor64.exe /compile:MQL5\\Experts\\AurumAI_Executor.mq5 /log:MQL5\\Experts\\compile.log' && sleep 2 && sudo docker exec ai-mt5-vnc ls -la '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/'"
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}
