#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 {
sudo docker exec ai-mt5-vnc bash -c "DISPLAY=:1 xdotool mousemove 65 460 click --repeat 2 --delay 100 1"
sleep 1.5
sudo docker exec ai-mt5-vnc bash -c "DISPLAY=:1 xdotool key Return"
sleep 2
today=$(date +%Y%m%d)
sudo docker exec ai-mt5-vnc bash -c "iconv -f UTF-16LE -t UTF-8 '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/logs/'$today.log | tail -n 25"
}
expect {
    "password:" { send "thunder-29%-quantum\r"; exp_continue }
    eof
}
