#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235
expect "password:"
send "thunder-29%-quantum\r"

expect "\\$ "
send "sudo docker rm -f ai-backend\r"

expect "\\$ "
send "sudo docker run -d --name ai-backend --restart always -p 3002:3002 -v /home/ubuntu/TradingAnalis/backend/data:/app/data --env-file /home/ubuntu/TradingAnalis/backend/.env ai-trading-backend\r"

expect "\\$ "
send "sudo docker logs -f --tail 20 ai-backend\r"

expect "\\$ "
send "exit\r"

expect eof
