#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235
expect "password:"
send "thunder-29%-quantum\r"

expect "\\$ "
send "cd /home/ubuntu/TradingAnalis && git pull\r"

expect "\\$ "
send "cd /home/ubuntu/TradingAnalis/backend && sudo docker build -t ai-trading-backend . && sudo docker rm -f ai-backend && sudo docker run -d --name ai-backend --restart always -p 3002:3002 -v /home/ubuntu/TradingAnalis/backend/data:/app/data --env-file .env ai-trading-backend\r"

expect "password for ubuntu:"
send "thunder-29%-quantum\r"

expect "\\$ "
send "exit\r"
expect eof
