#!/usr/bin/expect -f
set timeout 45
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 {
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool search --name "MetaEditor" windowactivate --sync
sleep 1
# Close current editor tab
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool key ctrl+F4
sleep 1
# Open Navigator -> Double click file OR Open dialog
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool key ctrl+o
sleep 1.5
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool key ctrl+a
sleep 0.5
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool type "C:\\Program Files\\MetaTrader 5\\MQL5\\Experts\\AurumAI_Executor.mq5"
sleep 1
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool key Return
sleep 2
# Press F7 to compile
sudo docker exec -u kasm-user -e DISPLAY=:1 ai-mt5-vnc xdotool key F7
sleep 4
sudo docker exec ai-mt5-vnc ls -la '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/'
}
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}
