#!/usr/bin/expect -f
set timeout 40

spawn scp -o StrictHostKeyChecking=no /Users/badrinteractive/Documents/TradingAnalis/mt5/AurumAI_Executor.mq5 ubuntu@43.156.79.235:/tmp/AurumAI_Executor.mq5
expect {
    "password:" { send "thunder-29%-quantum\r"; exp_continue }
    eof
}

spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 {
    sudo docker cp /tmp/AurumAI_Executor.mq5 "ai-mt5-vnc:/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/AurumAI_Executor.mq5"
    sudo docker exec -u root ai-mt5-vnc chown -R kasm-user:kasm-user "/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/AurumAI_Executor.mq5"
    sudo docker exec ai-mt5-vnc ls -la "/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/AurumAI_Executor.mq5"
}
expect {
    "password:" { send "thunder-29%-quantum\r"; exp_continue }
    eof
}
