#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 "sudo docker exec -u kasm-user -e DISPLAY=:1 -e WINEPREFIX=/headless/.wine ai-mt5-vnc wine '/headless/.wine/drive_c/Program Files/MetaTrader 5/metaeditor64.exe' '/compile:C:\\Program Files\\MetaTrader 5\\MQL5\\Experts\\AurumAI_Executor.mq5' '/log:C:\\Program Files\\MetaTrader 5\\MQL5\\Experts\\compile.log' && sleep 2 && sudo docker exec ai-mt5-vnc iconv -f UTF-16LE -t UTF-8 '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/compile.log'"
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}
