#!/usr/bin/expect -f
set timeout 30
spawn scp -o StrictHostKeyChecking=no ./mt5/AurumAI_Executor.ex5 ubuntu@43.156.79.235:/tmp/AurumAI_Executor.ex5
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}

spawn ssh -o StrictHostKeyChecking=no ubuntu@43.156.79.235 "sudo docker cp /tmp/AurumAI_Executor.ex5 ai-mt5-vnc:'/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/AurumAI_Executor.ex5' && sudo docker exec ai-mt5-vnc chown -R kasm-user:kasm-user '/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/'"
expect {
    "password:" {
        send "thunder-29%-quantum\r"
        exp_continue
    }
    eof
}
